import { readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

// Resolve the ordered source modules once during build, not in the browser.
export async function buildCss() {
  const root = resolve(dirname(fileURLToPath(import.meta.url)), '../assets/css');
  const manifest = await readFile(resolve(root, 'entry.css'), 'utf8');
  const imports = [...manifest.matchAll(/@import url\("([^"?]+)(?:\?[^"\n]*)?"\);/g)];
  const seen = new Set();
  const chunks = ['/* Generated by scripts/build-css.mjs. Edit entry.css or source modules. */'];
  for (const [, name] of imports) {
    const file = resolve(root, name);
    if (seen.has(file)) throw new Error(`Duplicate CSS module: ${name}`);
    if (relative(root, file).startsWith('..')) throw new Error(`Invalid CSS module: ${name}`);
    seen.add(file);
    let source = await readFile(file, 'utf8');
    if (/@import\b/.test(source)) throw new Error(`Nested CSS import: ${name}`);
    source = source.replace(/url\(\s*["']?([^"')]+)["']?\s*\)/g, (match, url) => {
      if (/^(\/|data:|https?:|#)/.test(url)) return match;
      const rebased = relative(root, resolve(dirname(file), url)).split('\\').join('/');
      return `url("${rebased}")`;
    });
    chunks.push(`/* Source: ${name} */\n${source.trim()}`);
  }
  if (!imports.length) throw new Error('CSS manifest is empty');
  await writeFile(resolve(root, 'main.css'), `${chunks.join('\n\n')}\n`);
}
